Сбор и публикация метрики покрытия unit-тестами
DotNetRu/Auditor pull request #22
Opened 2021-07-10 21:15 UTC by zetroot

Как обсуждалось в #19, добавил сборку покрытия тестами для проектов тестирования. Публикация результатов - на [codecov](https://app.codecov.io/gh/DotNetRu).
Появится, когда будет сборка для ветки `master`.
Что сделано:
 - обновил тестовые sdk
 - обновил пакеты сборщика метрик `coverlet.collector`
 - добавил сборку покрытия в шаге тестирования в pipeline `Smoke`
 - добавил шаг публикации покрытия в pipeline `Smoke`
 - добавил сборку покрытия в шаге тестирования в pipeline `Publish`
 - добавил шаг публикации покрытия в pipeline `Publish`
 - добавил badge от codecov в `README.md` (бейджик заработает, когда отработает `smoke.yaml` для ветки `master`)

2021-07-10 21:21 UTC, zetroot commented
> ❗ No coverage uploaded for pull request base (`master@a37900a`).
> The diff coverage is `n/a`.

[Это нормально для текущего состояния](https://docs.codecov.com/docs/error-reference#section-missing-base-commit) - не было еще ни одной загрузки code coverage.

2021-07-12 21:23 UTC, kulakovt commented
Спасибо :+1:

2021-07-12 21:44 UTC, kulakovt requested changes

2021-07-12 21:44 UTC, kulakovt commented on .github/workflows/Publish.yml
> +      uses: codecov/codecov-action@v1
Давай в `Publish` не будем собирать (и отсылать) покрытие?
Обычно оно будет совпадать с последним Smoke. Т.е. никакого смысла не имеет.

2021-07-12 21:44 UTC, kulakovt commented on README.md
Кто владелец учётной записи на `codecov.io/gh/DotNetRu`? Как получить доступ к админке?

2021-07-13 04:25 UTC, zetroot commented on README.md
Я так понимаю, что тот же кто и владелец организации на Github - некто @kulakovt 
Попробуй sign in под своим github аккаунтом туда.

Вот что они пишут по этому поводу:
> Codecov uses GitHub permissions to authenticate users. No setup necessary.
>Ask your team members to simply login to Codecov and they will have read/write access to the appropriate repositories.

2021-07-13 04:26 UTC, zetroot commented on .github/workflows/Publish.yml
> +      uses: codecov/codecov-action@v1
Да, пожалуй ты прав - smoke запускается всегда при изменении кода.

2021-07-13 17:03 UTC, kulakovt commented on .github/workflows/Publish.yml
> +
Наверное это не нужные изменения?

2021-07-13 17:09 UTC, kulakovt requested changes

2021-07-13 17:09 UTC, kulakovt commented on README.md
Что-то странное. При попытке log-in'а она просит у меня разрешение на изменение хуков и статусов коммитов. Буд-то я привязываю уже репозиторий к покрытию. Нельзя просто так зайти и посмотреть. У тебя такое было?

2021-07-13 21:58 UTC, zetroot commented on .github/workflows/Publish.yml
> +
да, ты абсолютно прав!

2021-07-13 22:09 UTC, zetroot commented on README.md
Да, я дропунл все доступы от codecov - и оно просит те же разрешения.

2021-07-14 18:01 UTC, merged