Aync File System
DotNetRu/Auditor pull request #8
Opened 2021-06-10 21:13 UTC by kulakovt

2021-06-10 21:20 UTC, kulakovt commented
@zetroot

2021-06-11 09:32 UTC, zetroot requested changes
Как обсуждали - добавил `ValueTask<>` в получение `Stream` для чтения. Что ты думаешь на этот счёт?

2021-06-11 09:32 UTC, zetroot commented on src/Storage/FileSystem/NotFoundFile.cs
> +        public Stream OpenForRead() => throw ToException(FullName);
```suggestion
        public ValueTask<Stream> OpenForRead() => throw ToException(FullName);
```

2021-06-11 09:32 UTC, zetroot commented on src/Storage/FileSystem/NotFoundFile.cs
> +        public Stream OpenForWrite() => throw ToException(FullName);
```suggestion
        public ValueTask<Stream> OpenForWrite() => throw ToException(FullName);
```

2021-06-11 09:32 UTC, zetroot commented on src/Storage/FileSystem/IFile.cs
> +
```suggestion
using System.Threading.Tasks;

```

2021-06-11 09:32 UTC, zetroot commented on src/Storage/FileSystem/Physical/PhysicalFile.cs
> +
```suggestion
using System.Threading.Tasks;

```

2021-06-11 09:32 UTC, zetroot commented on src/Storage/FileSystem/Physical/PhysicalFile.cs
> +        public Stream OpenForRead()
```suggestion
        public ValueTask<Stream> OpenForRead()
```

2021-06-11 09:32 UTC, zetroot commented on src/Storage/FileSystem/Physical/PhysicalFile.cs
> +        public Stream OpenForWrite()
```suggestion
        public ValueTask<Stream> OpenForWrite()
```

2021-06-11 09:32 UTC, zetroot commented on src/Storage/FileSystem/Physical/PhysicalFile.cs
> +            return File.OpenWrite(FullName);
```suggestion
            return new ValueTask<Stream>(File.OpenWrite(FullName));
```
Возможно, это не самый правильный способ создать `ValueTask<>`, но я не знаю про другие

2021-06-11 09:32 UTC, zetroot commented on src/Storage/FileSystem/Physical/PhysicalFile.cs
> +            return File.OpenRead(FullName);
```suggestion
            return new ValueTask<Stream>(File.OpenRead(FullName));
```

2021-06-11 09:32 UTC, zetroot commented on src/test/Tests/Storage/FileSystem/FileSystemEntryTest.cs
> +        [InlineData(@"C:\1", @".\Abc", @"C:\1\Abc")]
Посмотри мой PR в эту ветку #9 
Сейчас ломается на не-Windows машинах

2021-06-11 09:32 UTC, zetroot commented on src/test/Tests/Storage/FileSystem/FileSystemEntryTest.cs
> +            const string root = @"C:\A\B";
То же что и выше
#9

2021-06-11 20:00 UTC, kulakovt commented on src/Storage/FileSystem/IFile.cs
> +        Stream OpenForWrite();
Да, возвращать `Stream` асинхронно — хорошая идея.
`ValueTask ` тоже будут в тему, ибо никто кроме HTTP Client'а не будет реализовывать настоящую асинхронность.

2021-06-11 20:02 UTC, kulakovt commented on src/Storage/FileSystem/Physical/PhysicalFile.cs
> +            return File.OpenWrite(FullName);
Обычно делают:
`ValueTask.FromResult(x)`
Это позволяет выводить дженерик параметр. Но в данном случае всё едино.

2021-06-11 20:03 UTC, kulakovt commented on src/test/Tests/Storage/FileSystem/FileSystemEntryTest.cs
> +        [InlineData(@"C:\1", @".\Abc", @"C:\1\Abc")]
Вмёржил, спасибо

2021-06-11 20:04 UTC, kulakovt commented
> ValueTask<> в получение Stream

Сделал

2021-06-11 21:24 UTC, merged

2021-06-11 21:52 UTC, zetroot commented
🎉